# Generated by Django 4.0.6 on 2022-07-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='keyUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdata', verbose_name='Собеседник'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='keyUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdata', verbose_name='Собеседник'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='keyUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdata', verbose_name='Собеседник'),
        ),
    ]
