# Generated by Django 4.0.6 on 2022-07-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classificators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, unique=True, verbose_name='Название бота')),
                ('token', models.CharField(max_length=50, unique=True, verbose_name='Токен')),
                ('url', models.CharField(max_length=100, unique=True, verbose_name='Ссылка на бота')),
                ('active', models.BooleanField(default=False, verbose_name='Работает')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classificators.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Телеграм бот',
                'verbose_name_plural': 'Телеграм боты',
            },
        ),
    ]
