# Generated by Django 4.0.6 on 2022-07-26 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classificators', '0001_initial'),
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classificators.project', verbose_name='Проект'),
        ),
    ]
