# Generated by Django 4.0.6 on 2022-08-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_telegrambot_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='tg_id',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Telegram ID бота'),
        ),
    ]
