# Generated by Django 4.0.6 on 2022-07-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0002_alter_telegrambot_project'),
        ('classificators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, verbose_name='Текст команды (start, напимер)')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст реакции на команду (не обязательно)')),
                ('delay', models.IntegerField(default=0, verbose_name='Задержка реакции, сек')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.telegrambot', verbose_name='Бот')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classificators.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
