# Generated by Django 4.0.6 on 2022-08-02 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_telegrambot_tg_id'),
        ('reactions', '0002_keyboardbutton_remove_command_project_keyboard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='caption',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default='0000000000', max_length=50, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='tag_action',
            field=models.CharField(choices=[('NONE', 'Без изменений'), ('ADD', 'Добавить'), ('REM', 'Удалить')], default='NONE', max_length=5, verbose_name='Тэги пользователя'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст реакции (не обязательно)'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateID', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.telegrambot', verbose_name='Бот')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reactions.state', verbose_name='Позиция'),
        ),
    ]
