# Generated by Django 4.0.6 on 2022-08-02 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0003_remove_answer_caption_answer_answer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='from_button',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reactions.keyboardbutton', verbose_name='По кнопке'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default='new_state', max_length=50, unique=True, verbose_name='Идентификатор'),
        ),
    ]
