# Generated by Django 4.0.6 on 2022-08-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0004_answer_from_button_alter_answer_answer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyboard',
            name='language',
        ),
        migrations.RemoveField(
            model_name='keyboardbutton',
            name='language',
        ),
        migrations.AddField(
            model_name='keyboard',
            name='type',
            field=models.CharField(choices=[('std', 'Стандартная'), ('inl', 'Инлайн')], default='std', max_length=5, verbose_name='Тип клавиатуры'),
        ),
    ]
