# Generated by Django 4.0.6 on 2022-07-25 14:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=100, verbose_name='Название тэга')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет учёта тэга (чем больше, тем приоритетнее)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classificators.project', verbose_name='Тэг проекта')),
            ],
            options={
                'verbose_name': 'Тэг пользователей',
                'verbose_name_plural': 'Тэги пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=100, verbose_name='Название группы')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classificators.project', verbose_name='Группа пользователей проекта')),
            ],
            options={
                'verbose_name': 'Группа пользователей',
                'verbose_name_plural': 'Группы пользователей',
            },
        ),
    ]
